### ISSUE TITLE
This expression is not constructable.

### ISSUE THREAD

**Issue by dmitriyzhuk** [radzserg/rsdi3#3]
```
This expression is not constructable.
  Type 'typeof import("..../node_modules/rsdi/dist/index")' has no construct signatures.ts
```

based on the documentation DIContainer should be the default export.  
```
import DIContainer from 'rsdi';

export type AppDIContainer = ReturnType<typeof configureDI>;
...
```

but if we check the code, it is a named export  https://github.com/radzserg/rsdi3/blob/main/src/DIContainer.ts

line 21 `export class DIContainer<ContainerResolvers extends ResolvedDependencies = {}> {` 

`import { DIContainer}  from 'rsdi';`

fixes it.

**Comment by radzserg** [comment]
Good catch. Documentation has been migrated from the previous version. I'll make an update.

**Comment by radzserg** [comment]
Updated `readme.md` https://github.com/radzserg/rsdi3/pull/4 
A new version 3.0.3 has been released.
