### ISSUE TITLE
Error: require() of ES Module node_modules\rsdi\dist\index.js

### ISSUE THREAD

**Issue by pedro-lima-reis** [radzserg/rsdi3#5]
I need some help with this:
```cmd 
[ERROR] 01:43:45 Error: require() of ES Module \node_modules\rsdi\dist\index.js from \src\infrastructure\di.ts not supported.
Instead change the require of index.js in \src\infrastructure\di.ts to a dynamic import() which is available in all CommonJS modules.
```
I updated the version and make all adjustments needed

**Comment by radzserg** [comment]
@pedro-lima-reis what version of node do you use and can you share your package.json file please

**Comment by jdiaz-wcslat** [comment]
@radzserg i have the same problem

nodejs v20.4.0

`"devDependencies": {
    "@commitlint/cli": "^17.7.1",
    "@commitlint/config-conventional": "^17.7.0",
    "@types/config": "^3.3.0",
    "@types/dotenv": "^8.2.0",
    "@types/express": "^4.17.20",
    "@types/lodash": "^4.14.195",
    "@types/node": "^20.4.2",
    "@typescript-eslint/eslint-plugin": "^6.7.0",
    "@typescript-eslint/parser": "^6.7.0",
    "ts-node-dev": "^2.0.0",
    "tsx": "^3.12.7",
    "typescript": "^4.9.5"
  },
  "dependencies": {
    "@typegoose/typegoose": "^11.3.0",
    "body-parser": "^1.20.1",
    "config": "^3.3.9",
    "dotenv": "^16.3.1",
    "express": "^4.18.2",
    "rsdi": "^3.0.3",
    "zod": "^3.21.4"
  }
  `

**Comment by pedro-lima-reis** [comment]
v18.17.1

**Comment by paulo123araujo** [comment]
@pedro-lima-reis did you try to bundle your application to `esm` and not to `commonjs`?

A time ago i faced this same kinda of problem, and i solve changing the way my application was built.

just to exemplify, I use these configs:

```ts
// tsup.config.ts
import { defineConfig } from 'tsup';

export default defineConfig({
  tsconfig: './tsconfig.json',
  entry: ['./src/**/*.ts'],
  splitting: true,
  sourcemap: true,
  clean: true,
  platform: 'node',
  esbuildOptions(options, _context) {
    // the directory structure will be the same as the source
    options.outbase = './src';
  },
  target: 'node20',
  format: 'esm',
  treeshake: true,
  outDir: 'build',
});
```

```json
// tsconfig.json
{
    "compilerOptions": {
        "types": ["node"],
        "module": "ESNext",
        "moduleResolution": "Node",
        "target": "ES2020",
        "baseUrl": ".",
        "outDir": "build",
        "esModuleInterop": true,
        "strict": true,
        "resolveJsonModule": true,
        "skipLibCheck": true,
        "sourceMap": true,
        "forceConsistentCasingInFileNames": true,
        "allowJs": true,
        "rootDirs": ["src"],
        "lib": ["DOM", "ESNext"],
        "removeComments": true,
        "paths": {
            "@tests/*": ["./tests/*"],
            "@/*": ["./src/*"]
        },
        "typeRoots": ["./types"],
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "strictPropertyInitialization": false
    },
    "include": ["src", "tests"],
    "exclude": ["node_modules"]
}
```

and in package.json I set `"type": "module"`, and with all this settings the application worked on production.

Hope it helps.

**Comment by radzserg** [comment]
`"type": "module"` should do the trick. @jdiaz-wcslat  @pedro-lima-reis can you also share your package.json file. Thank you.

**Comment by radzserg** [comment]
I'm closing this issue for now, since we don't have much feedback.
